apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-backend
  labels:
    app: exam-backend
spec:
  selector:
    matchLabels:
      app: exam-backend
  replicas: 2 # 告知 Deployment 运行 2 个与该模板匹配的 Pod
  template:
    metadata:
      labels:
        app: exam-backend
    spec:
      containers:
        - name: exam-backend-container
          image: <backend-image-name>
          env:
            - name: DB_HOSTNAME
              value: "192.168.56.110"
            - name: REDIS_HOSTNAME
              value: "192.168.56.110"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: exam-backend-secret
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: exam-backend-secret
                  key: db_password
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: 500m
              memory: "128Mi"
          ports:
            - containerPort: 8888
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: exam-backend-service
spec:
  selector:
    app: exam-backend
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
# exam-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-frontend
  labels:
    app: exam-frontend
spec:
  selector:
    matchLabels:
      app: exam-frontend
  replicas: 1 # 告知 Deployment 运行 2 个与该模板匹配的 Pod
  template:
    metadata:
      labels:
        app: exam-frontend
    spec:
      containers:
        - name: exam-frontend-container
          image: <frontend-image-name>
          resources:
            limits:
              cpu: "1"
              memory: "256Mi"
            requests:
              cpu: 500m
              memory: "128Mi"
          ports:
            - containerPort: 8080
