---
apiVersion: v1
kind: Service
metadata:
  name: exam-backend-service
spec:
  selector:
    app: exam-backend
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: exam-frontend-service
spec:
  selector:
    app: exam-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
